/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package eu.kaszkowiak.tomahawk.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING_SQ = 4;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int ENDLINE = 8;
  /** RegularExpression Id. */
  int INCLUDE = 9;
  /** RegularExpression Id. */
  int USE = 10;
  /** RegularExpression Id. */
  int PARAM = 11;
  /** RegularExpression Id. */
  int LEFT_CROC = 12;
  /** RegularExpression Id. */
  int RIGHT_CROC = 13;
  /** RegularExpression Id. */
  int LEFT_ENDING_CROC = 14;
  /** RegularExpression Id. */
  int WHITESPACE = 15;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING_STATE = 1;
  /** Lexical state. */
  int IN_COMMENT_STATE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\"\"",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"\\\"\"",
    "\"#\"",
    "<token of kind 6>",
    "<COMMENT>",
    "<ENDLINE>",
    "\"Include\"",
    "\"Use\"",
    "<PARAM>",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "<WHITESPACE>",
  };

}
